/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#ff5c45",
        "surface-container-highest": "#e5e2dd",
        "background": "#fcf9f4",
        "surface-container-low": "#f6f3ee",
        "surface-dim": "#dcdad5",
        "secondary-fixed-dim": "#ffb4a7",
        "on-error-container": "#93000a",
        "secondary": "#b52617",
        "error-container": "#ffdad6",
        "surface-container": "#f0ede9",
        "primary": "#000000",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#4a4640",
        "on-error": "#ffffff",
        "surface": "#fcf9f4",
        "on-secondary": "#ffffff",
        "inverse-surface": "#31302d",
        "primary-fixed-dim": "#cbc5c0",
        "inverse-on-surface": "#f3f0eb",
        "surface-tint": "#615e5a",
        "tertiary-container": "#1e1b16",
        "on-tertiary-container": "#89837b",
        "outline-variant": "#cdc5bc",
        "surface-container-high": "#ebe8e3",
        "surface-variant": "#e5e2dd",
        "secondary-fixed": "#ffdad4",
        "on-secondary-fixed-variant": "#920701",
        "inverse-primary": "#cbc5c0",
        "on-tertiary-fixed": "#1e1b16",
        "primary-fixed": "#e8e1dc",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#cdc5bd",
        "tertiary": "#000000",
        "on-primary-container": "#87837f",
        "on-secondary-container": "#600200",
        "on-surface-variant": "#4b463f",
        "tertiary-fixed": "#e9e1d8",
        "outline": "#7c766e",
        "surface-bright": "#fcf9f4",
        "primary-container": "#1d1b18",
        "on-secondary-fixed": "#400100",
        "error": "#ba1a1a",
        "on-primary-fixed": "#1d1b18",
        "on-surface": "#1c1c19",
        "on-background": "#1c1c19",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#494643",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        gutter: "16px",
        "column-gap": "24px",
      },
      fontFamily: {
        "body-md": ['"Source Serif 4"'],
        "meta-mono": ["JetBrains Mono"],
        "label-caps": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ['"Source Serif 4"'],
        "headline-display": ['"Source Serif 4"'],
        "body-lg": ['"Source Serif 4"'],
        "headline-lg": ['"Source Serif 4"'],
        "headline-lg-mobile": ['"Source Serif 4"'],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "meta-mono": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-display": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "28px", fontWeight: "700" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
